name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bumpPart:
        description: 'Bump part (major, minor or patch)'
        required: true
        default: "minor"

jobs:
  bump:
    name: Bump App Version
    runs-on: ubuntu-latest
    # Sanity check on the input
    if: contains(['major', 'minor', 'patch'], ${{ github.event.inputs.bumpPart }})
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        id: bumpversion
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bumpPart }}
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "$remote_repo" HEAD:"${GITHUB_REF#refs/heads/}"