name: CI

on:
  push:
    paths-ignore:
      - '.github/workflows/manual-release.yml'

jobs:
  bundle-app:
    name: Bundle App
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.appinfo.outputs.app_name }}
      app_id: ${{ steps.appinfo.outputs.app_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Read App Info
        id: appinfo
        run: |
          APP_ID=$(cat app.manifest | jq -r '.info.id.name')
          echo "app_id=${APP_ID}" >> $GITHUB_OUTPUT
          APP_NAME=$(echo "$APP_ID" | tr _ - )
          echo "app_name=${APP_NAME}" >> $GITHUB_OUTPUT

      - name: Exclude images from README
        run: |
          sed -i '/^!/d' README.md

      - name: Bundle app source
        run: |
          mkdir dist
          tar -zcvf dist/${{ steps.appinfo.outputs.app_name }}.tgz --exclude='.[^/]*' --exclude=./dist .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged_app
          path: dist/${{ steps.appinfo.outputs.app_name }}.tgz

  slim-validate:
    name: SLIM Validation
    needs: bundle-app
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.7, 3.9 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged_app

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install splunk-packaging-toolkit

      - name: Slim Validate
        run: slim validate *.tgz

  appinspect-cli:
    name: AppInspect CLI ${{ matrix.tags }}
    needs: bundle-app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - "cloud"
          - "private_app"
          - "private_classic"
          - "private_victoria"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packaged_app
          path: dist
      - uses: splunk/appinspect-cli-action@v2.10
        with:
          app_path: dist
          included_tags: ${{ matrix.tags }}

  # appinspect-api:
  #   name: AppInspect API Validation
  #   needs:
  #     - bundle-app
  #     - appinspect-cli
  #     - slim-validate
  #   runs-on: ubuntu-latest
  #   # Job not executed if branch is not master
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: app_tgz

  #     - name: Run AppInspect
  #       uses: splunk/appinspect-api-action@v2
  #       with:
  #         filePath: ${{ needs.bundle-app.outputs.app_name }}.tgz
  #         splunkUser: ${{ secrets.SPLUNK_USER }}
  #         splunkPassword: ${{ secrets.SPLUNK_PASS }}
  #         includedTags: cloud
  #         failOnError: true
  #         failOnWarning: false